services:
  - type: web
    name: sureride-admin-backend
    env: node
    plan: starter
    region: frankfurt
    branch: main

    buildCommand: npm install && npm run build
    startCommand: npm run prisma:migrate && npm start

    healthCheckPath: /health
    autoDeploy: true

    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: sureride-db
          property: internalConnectionString # ðŸ”¥ FIX

databases:
  - name: sureride-db
    plan: basic-1gb
    region: frankfurt
